### ISSUE TITLE
Duplicate id PR_P0DTC4

### ISSUE THREAD

**Issue by janelomax** [CIDO-ontology/cido#45] opened 2024-02-14 14:29 UTC
Hi - I'm pretty sure I reported this before, but it doesn't seem to be fixed. There are two different URIs for PR_P0DTC4 as shown in the screenshots below from the current OLS version. Please can this be resolved - we get an error from our pipeline at every update for this. Thanks!

<img width="671" alt="Screenshot 2024-02-14 at 14 25 01" src="https://github.com/CIDO-ontology/cido/assets/6639811/2f9afc6c-90cd-4b28-8a65-42cea4c3b6f1">
<img width="1014" alt="Screenshot 2024-02-14 at 14 26 26" src="https://github.com/CIDO-ontology/cido/assets/6639811/8ec968a9-76d3-4974-b997-577c3f2110ac">

**Comment by yongqunh** [comment] 2024-02-15 04:40
Got it. Will be working on this soon. Thanks, Oliver

**Comment by zhengj2007** [comment] 2024-02-15 18:16
The issue caused by import terms from VO with wrong IRI assigned to term: PR_P0DTC4

**Comment by zhengj2007** [comment] 2024-02-16 17:47
Fixed

**Closed by zhengj2007** 2024-02-16 17:47 UTC
